trigger:
  - master

schedules:
  - cron: "30 6 * * 0"   # 12:00 PM IST = 6:30 AM UTC every Sunday
    displayName: Sunday Noon IST
    branches:
      include:
        - master
    always: true  # Run even with no recent commits

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/junitreports/*.xml'
      goals: 'clean test'
      options: '-Dsurefire.suiteXmlFiles=src/test/config/failTest.xml'
      continueOnError: true
    env:
      BROWSERSTACK_USERNAME: $(BROWSERSTACK_USERNAME)
      BROWSERSTACK_ACCESS_KEY: $(BROWSERSTACK_ACCESS_KEY)
      BROWSERSTACK_PROJECT: $(BROWSERSTACK_PROJECT)
      BROWSERSTACK_BUILD: $(BROWSERSTACK_BUILD)
      BROWSERSTACK_NAME: $(BROWSERSTACK_NAME)

  - task: CopyFiles@2
    condition: always()
    inputs:
      contents: 'target/surefire-reports/junitreports/*.xml'
      targetFolder: '$(Build.ArtifactStagingDirectory)/junitreports'

  - task: PublishBuildArtifacts@1
    condition: always()
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)/junitreports'
      artifactName: 'JUnitReports'
      publishLocation: 'Container'
