name: QEI Fail JOB PREPROD

on:
  workflow_dispatch:
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    env :
      BROWSERSTACK_USERNAME_PRE_PROD: ${{ secrets.BROWSERSTACK_USERNAME_PRE_PROD }}
      BROWSERSTACK_ACCESS_KEY_PRE_PROD: ${{ secrets.BROWSERSTACK_ACCESS_KEY_PRE_PROD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

    

      - name: Set BrowserStack Environment Variables
        run: |
          echo "BROWSERSTACK_PROJECT=QEI FAILING JOB" >> $GITHUB_ENV
          echo "BROWSERSTACK_BUILD=Build-QEI-FAILING-JOB" >> $GITHUB_ENV
          echo "BROWSERSTACK_NAME=FAILING-JOB-TEST" >> $GITHUB_ENV
          echo "BROWSERSTACK_ENV=preprod" >> $GITHUB_ENV
      - name: Build and Test with Maven
        run: mvn clean test "-Dsurefire.suiteXmlFiles=src/test/config/failTest.xml"

      - name: Archive TestNG Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: testng-junit-report_test1
          path: target
