name: QEI-Parent-Child-Job Workflow Preprod

on:
  workflow_dispatch:
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    env :
      BROWSERSTACK_USERNAME_PRE_PROD: ${{ secrets.BROWSERSTACK_USERNAME_PRE_PROD }}
      BROWSERSTACK_ACCESS_KEY_PRE_PROD: ${{ secrets.BROWSERSTACK_ACCESS_KEY_PRE_PROD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven



      - name: Set BrowserStack Environment Variables
        run: |
          echo "BROWSERSTACK_PROJECT=QEI-PARENT-CHILD-JOB" >> $GITHUB_ENV
          echo "BROWSERSTACK_BUILD=Build-QEI-PARENT-CHILD-JOB" >> $GITHUB_ENV
          echo "BROWSERSTACK_NAME=PARENT-CHILD-JOB-TEST" >> $GITHUB_ENV
          echo "BROWSERSTACK_ENV=preprod" >> $GITHUB_ENV

      - name: Build with Maven
        run: mvn clean test -Dsurefire.suiteXmlFiles=src/test/config/passTest.xml

      - name: Archive TestNG Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: testng-junit-report_first
          path: target

  SecondTest:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup BrowserStack Environment
        uses: browserstack/github-actions/setup-env@master
        with:
          username: ${{ secrets.BROWSERSTACK_ACCESS_KEY_PRE_PROD }}
          access-key: ${{ secrets.BROWSERSTACK_USERNAME_PRE_PROD }}

      - name: Set BrowserStack Environment Variables
        run: |
          echo "BROWSERSTACK_PROJECT=QEI-PARENT-CHILD-JOB" >> $GITHUB_ENV
          echo "BROWSERSTACK_BUILD=Build-QEI-PARENT-CHILD-JOB" >> $GITHUB_ENV
          echo "BROWSERSTACK_NAME=PARENT-CHILD-JOB-TEST" >> $GITHUB_ENV
          echo "BROWSERSTACK_ENV=preprod" >> $GITHUB_ENV

      - name: Build with Maven
        run: mvn clean test -Dsurefire.suiteXmlFiles=src/test/config/failTest.xml

      - name: Archive TestNG Results (Second Job)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: testng-junit-report_second
          path: target
