name: QEI-Parent-Child-Job workflow

on:
  workflow_dispatch

jobs:
  FirstTest:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file


      - name: Run tests
        run: |
          echo ${{ secrets.BROWSERSTACK_USERNAME }}
          echo ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
     
    
      - name: Setup Browserstack env
        uses: browserstack/github-actions/setup-env@O11y-Rerun-Staging
        with:
          username:  ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          github-app: 'bstack-integrations-staging[bot]'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests 2
        run: |
          echo "Env variable is: ${{ env }}"
      - name: Build with Maven
        run:  mvn clean test -Dsurefire.suiteXmlFiles=config/passtest.xml

      - name: Archive code TestNG results
        uses: actions/upload-artifact@v4
        if: always()
        with:  
          name: testng-junit-report_test1
          path: target
          
          

  SecondTest:

    runs-on: ubuntu-latest
    needs: FirstTest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Setup Browserstack env
        uses: browserstack/github-actions/setup-env@O11y-Rerun-Staging
        with:
          username:  ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          github-app: 'bstack-integrations-staging[bot]'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build with Maven
        run:  mvn clean test -Dsurefire.suiteXmlFiles=config/failtest.xml

      - name: Archive code TestNG second Job results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: testng-junit-report
          path: target  
